title: Studdy Buddy
description: An application to find study buddies
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions

plugins:
  - jekyll-mermaid

# Inject custom CSS into the head of your pages
defaults:
  - scope:
      path: ""
    values:
      head:
        - |
          <style>
            body {
              background-color: #2f2f2f; /* Dark grey background */
              color: #f1f1f1; /* Light text color for readability */
            }
          </style>
